const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Mouse,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Browser,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{direcao: 0},
	{"8Direções": 0},
	{Protagonista: 0},
	{CentrarEm: 0},
	{Mira: 0},
	{Mouse: 0},
	{Fixar: 0},
	{Camera: 0},
	{Teclado: 0},
	{Sprite: 0},
	{Sólido: 0},
	{Mosaico: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{iniciar: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Mosaico2: 0},
	{Sprite9: 0},
	{inimigo: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{tentarnovamente: 0},
	{menu: 0},
	{Navegador: 0},
	{Sprite13: 0},
	{saida: 0},
	{Inimigo2: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{EsterEGG: 0},
	{seta: 0},
	{Sprite17: 0}
];

self.InstanceType = {
	Protagonista: class extends self.ISpriteInstance {},
	Mira: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	iniciar: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	inimigo: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	tentarnovamente: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	saida: class extends self.ISpriteInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	EsterEGG: class extends self.ISpriteInstance {},
	seta: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {}
}